databases:
  - name: todos
    databaseName: todos
    user: todos
    plan: free

services:
  - type: web
    name: todos
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "rackup -p 3000"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: todos
          property: connectionString
      - key: ENV
        value: production